In [2]:
# Core libraries for this lecture
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
# Read the CSV into a DataFrame.
# If this ever raises UnicodeDecodeError on another file, try encoding="latin1".
sales = pd.read_csv("Sample-Superstore2019.csv",
                    parse_dates=["Order Date", "Ship Date"],
                    usecols=cols)
sales

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2018-138688,2018-06-12,2018-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2016-110422,2016-01-21,2016-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2019-119914,2019-05-04,2019-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [10]:
sales.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9994 non-null   int64
 1   Row ID          9994 non-null   int64
 2   Order ID        9994 non-null   str
 3   Order Date      9994 non-null   datetime64[us]
 4   Ship Date       9994 non-null   datetime64[us]
 5   Ship Mode       9994 non-null   str
 6   Customer ID     9994 non-null   str
 7   Customer Name   9994 non-null   str
 8   Segment         9994 non-null   str
 9   Country/Region  9994 non-null   str
 10  City            9994 non-null   str
 11  State           9994 non-null   str
 12  Postal Code     9983 non-null   float64
 13  Region          9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Category        9994 non-null   str
 16  Sub-Category    9994 non-null   str
 17  Product Name    9994 non-null   str
 18  Sales           9994 non-null   float64
 19  Quantity        9994 non-null   int64
 20  Discount        9994 non-null   float64
 21  Profit          9994 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(3), str(13)
memory usage: 8.3 MB

In [4]:
# Quick confirmation that the file loaded and how big it is (rows, columns)
sales.shape

(9994, 22)

In [12]:
sales.head(13)

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,0,1,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,1,2,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,2,3,CA-2018-138688,2018-06-12,2018-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,3,4,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,4,5,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,5,6,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,6,7,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,7,8,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,8,9,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,9,10,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700
10,10,11,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
11,11,12,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568
12,12,13,CA-2019-114412,2019-04-15,2019-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,United States,...,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,3,0.20,5.4432

In [13]:
sales.tail()

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9989,9990,CA-2016-110422,2016-01-21,2016-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9990,9991,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9991,9992,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9992,9993,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9993,9994,CA-2019-119914,2019-05-04,2019-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [ ]:
sample_1 = sales.sample(10)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
8407,CA-2019-140480,2019-07-08,2019-07-12,Standard Class,HE-14800,Harold Engle,Corporate,United States,Newark,Delaware,19711.0,East,OFF-AR-10001419,Office Supplies,Art,Newell 325,28.910,7,0.0,8.6730
726,CA-2019-144113,2019-09-16,2019-09-20,Standard Class,JF-15355,Jay Fein,Consumer,United States,Austin,Texas,78745.0,Central,TEC-PH-10002170,Technology,Phones,ClearSounds CSC500 Amplified Spirit Phone Cord...,55.992,1,0.2,5.5992
2562,CA-2017-144288,2017-12-25,2017-12-31,Standard Class,MB-17305,Maria Bertelson,Consumer,United States,Nashville,Tennessee,37211.0,South,OFF-PA-10002787,Office Supplies,Paper,Xerox 227,10.368,2,0.2,3.6288
775,CA-2019-104220,2019-01-30,2019-02-05,Standard Class,BV-11245,Benjamin Venier,Corporate,United States,Des Moines,Iowa,50315.0,Central,FUR-FU-10002597,Furniture,Furnishings,"C-Line Magnetic Cubicle Keepers, Clear Polypro...",34.580,7,0.0,14.5236
2800,CA-2018-153318,2018-10-25,2018-10-28,First Class,JS-15595,Jill Stevenson,Corporate,United States,Miami,Florida,33180.0,South,TEC-PH-10000984,Technology,Phones,Panasonic KX-TG9471B,783.960,5,0.2,78.3960
3882,CA-2017-129896,2017-06-15,2017-06-20,Standard Class,PF-19120,Peter Fuller,Consumer,United States,Gilbert,Arizona,85234.0,West,FUR-FU-10004904,Furniture,Furnishings,"Eldon ""L"" Workstation Diamond Chairmat",364.704,6,0.2,-36.4704
8139,CA-2018-102561,2018-07-18,2018-07-22,Standard Class,NK-18490,Neil Knudson,Home Office,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-ST-10001476,Office Supplies,Storage,Steel Personal Filing/Posting Tote,284.080,10,0.2,24.8570
3569,CA-2019-168109,2019-07-03,2019-07-03,Same Day,JK-15640,Jim Kriz,Home Office,United States,Seattle,Washington,98105.0,West,TEC-MA-10001148,Technology,Machines,Okidata MB491 Multifunction Printer,2395.200,6,0.2,209.5800
2972,CA-2019-167941,2019-11-06,2019-11-09,Second Class,JF-15565,Jill Fjeld,Consumer,United States,Fayetteville,North Carolina,28314.0,South,OFF-ST-10000736,Office Supplies,Storage,Carina Double Wide Media Storage Towers in Nat...,259.136,4,0.2,-51.8272
539,CA-2017-134894,2017-12-07,2017-12-11,Standard Class,DK-12985,Darren Koutras,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10002647,Furniture,Chairs,"Situations Contoured Folding Chairs, 4/Set",283.920,4,0.0,70.9800

In [33]:
sample_1

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
8407,CA-2019-140480,2019-07-08,2019-07-12,Standard Class,HE-14800,Harold Engle,Corporate,United States,Newark,Delaware,19711.0,East,OFF-AR-10001419,Office Supplies,Art,Newell 325,28.910,7,0.0,8.6730
726,CA-2019-144113,2019-09-16,2019-09-20,Standard Class,JF-15355,Jay Fein,Consumer,United States,Austin,Texas,78745.0,Central,TEC-PH-10002170,Technology,Phones,ClearSounds CSC500 Amplified Spirit Phone Cord...,55.992,1,0.2,5.5992
2562,CA-2017-144288,2017-12-25,2017-12-31,Standard Class,MB-17305,Maria Bertelson,Consumer,United States,Nashville,Tennessee,37211.0,South,OFF-PA-10002787,Office Supplies,Paper,Xerox 227,10.368,2,0.2,3.6288
775,CA-2019-104220,2019-01-30,2019-02-05,Standard Class,BV-11245,Benjamin Venier,Corporate,United States,Des Moines,Iowa,50315.0,Central,FUR-FU-10002597,Furniture,Furnishings,"C-Line Magnetic Cubicle Keepers, Clear Polypro...",34.580,7,0.0,14.5236
2800,CA-2018-153318,2018-10-25,2018-10-28,First Class,JS-15595,Jill Stevenson,Corporate,United States,Miami,Florida,33180.0,South,TEC-PH-10000984,Technology,Phones,Panasonic KX-TG9471B,783.960,5,0.2,78.3960
3882,CA-2017-129896,2017-06-15,2017-06-20,Standard Class,PF-19120,Peter Fuller,Consumer,United States,Gilbert,Arizona,85234.0,West,FUR-FU-10004904,Furniture,Furnishings,"Eldon ""L"" Workstation Diamond Chairmat",364.704,6,0.2,-36.4704
8139,CA-2018-102561,2018-07-18,2018-07-22,Standard Class,NK-18490,Neil Knudson,Home Office,United States,Philadelphia,Pennsylvania,19140.0,East,OFF-ST-10001476,Office Supplies,Storage,Steel Personal Filing/Posting Tote,284.080,10,0.2,24.8570
3569,CA-2019-168109,2019-07-03,2019-07-03,Same Day,JK-15640,Jim Kriz,Home Office,United States,Seattle,Washington,98105.0,West,TEC-MA-10001148,Technology,Machines,Okidata MB491 Multifunction Printer,2395.200,6,0.2,209.5800
2972,CA-2019-167941,2019-11-06,2019-11-09,Second Class,JF-15565,Jill Fjeld,Consumer,United States,Fayetteville,North Carolina,28314.0,South,OFF-ST-10000736,Office Supplies,Storage,Carina Double Wide Media Storage Towers in Nat...,259.136,4,0.2,-51.8272
539,CA-2017-134894,2017-12-07,2017-12-11,Standard Class,DK-12985,Darren Koutras,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10002647,Furniture,Chairs,"Situations Contoured Folding Chairs, 4/Set",283.920,4,0.0,70.9800

In [ ]:
# Shape: (number of rows, number of columns)
print("Shape:", sales.shape)

In [ ]:
sales.tail()

In [ ]:
sales.sample(n=10, random_state=42)

In [ ]:
sales.columns.tolist()

In [30]:
cols = sales.columns.tolist()[2:]
cols

['Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country/Region',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [ ]:
# Column names
print(sales.columns.tolist())

# .info() gives dtypes + non-null counts + memory usage all at once
sales.info()

In [ ]:
# TODO 1: print the column names as a list


# TODO 2: display the first 7 rows


# TODO 3: inspect df.info() output and note the column(s) with missing values (write your answer as a comment)


# TODO 4: re-read the CSV using a read_csv parameter that avoids the Unnamed: 0 column

In [ ]:
# Summary stats for numeric columns: Sales, Quantity, Discount, Profit, Postal Code, Row ID...
sales.describe()

In [ ]:
# Summary stats for text/categorical columns
sales.describe(include="str")

In [ ]:
sales["Region"].value_counts()

In [ ]:
# How many orders per Region / Segment / Ship Mode?
print(sales["Region"].value_counts())
print()
print(sales["Segment"].value_counts())
print()
print(sales["Ship Mode"].value_counts())

In [ ]:
# TODO 1: describe() on Sales and Profit only


# TODO 2: value_counts() on Category


# TODO 3: value_counts(normalize=True) on Ship Mode


# TODO 4: comment on whether Discount's min/max look plausible

In [ ]:
# sales['Order Date'] = pd.to_datetime(sales['Order Date'])
sales["Shipping Days"] =(sales['Ship Date'] - sales['Order Date']).dt.days

In [ ]:
sales['Ship Date'].dt.day

In [ ]:
sales.head()

In [ ]:
# Convert the two date columns from text to real datetime objects
sales["Order Date"] = pd.to_datetime(sales["Order Date"])
sales["Ship Date"] = pd.to_datetime(sales["Ship Date"])

# Now that they're real dates, we can do date arithmetic:
# how many days did each order take to ship?
sales["Shipping Days"] = (sales["Ship Date"] - sales["Order Date"]).dt.days

sales[["Order Date", "Ship Date", "Shipping Days"]].head()

In [ ]:
sales.info(memory_usage='deep')

In [ ]:
sales.memory_usage(deep=True)

In [ ]:
sales["Country/Region"] = sales["Country/Region"].astype("category")

In [ ]:
sales.memory_usage(deep=True)

In [ ]:
# Pull the order month/year out now that Order Date is a real datetime
# sales["Order Month"] = sales["Order Date"].dt.month
# sales["Order Year"] = sales["Order Date"].dt.year

# Convert low-cardinality text columns to the 'category' dtype (memory + speed win)
for col in ["Segment", "Region", "Ship Mode", "Category", "Sub-Category"]:
    sales[col] = sales[col].astype("category")

sales.memory_usage(deep=True)

In [ ]:
sales.info(memory_usage='deep')

In [ ]:
# TODO 1: confirm Order Date's dtype


# TODO 2: create an "Order Weekday" column using .dt.day_name()


# TODO 3: compute the average Shipping Days


# TODO 4: convert Sub-Category to category dtype

In [ ]:
# Count missing values per column
sales.isnull().sum()

In [ ]:
sales[sales['Postal Code'].isnull()][["Country/Region", "Region", "State", "City"]]

In [ ]:
# Look at the actual rows with a missing Postal Code — is there a pattern?
sales[sales["Postal Code"].isnull()][["City", "State", "Postal Code"]]

In [ ]:
# All 11 missing postal codes belong to Burlington, Vermont.
# That's not random -- we can look up the real ZIP code (05401) and fill it in
# rather than dropping 11 otherwise-perfectly-good rows.
sales["Postal Code"] = sales["Postal Code"].fillna(5401)

# Confirm there are no missing values left in this column
sales["Postal Code"].isnull().sum()

In [ ]:
sales.isnull().sum()

In [ ]:
# TODO 1: confirm no missing values remain


# TODO 2: write (but don't overwrite df with) a dropna() call for Postal Code


# TODO 3: comment — when is dropping rows the wrong call?

In [ ]:
# Exact full-row duplicates
print("Exact duplicate rows:", df.duplicated().sum())

# Duplicates on a more meaningful subset: same order line for the same product
print("Duplicate Order ID + Product ID pairs:", df.duplicated(subset=["Order ID", "Product ID"]).sum())

In [ ]:
# Inspect what those subset-duplicates actually look like
dup_mask = df.duplicated(subset=["Order ID", "Product ID"], keep=False)
df[dup_mask].sort_values(["Order ID", "Product ID"]).head(8)

In [ ]:
# TODO 1: duplicated() on Customer ID + Order Date


# TODO 2: comment explaining keep="first" vs keep="last"


# TODO 3: name (and try) the method that would actually remove duplicate rows

In [ ]:
# Check every key categorical column for stray variants (casing, whitespace, typos)
for col in ["Segment", "Region", "Ship Mode", "Category", "Country/Region"]:
    print(col, "->", df[col].unique())

In [ ]:
# Even on a clean column, this is the defensive pattern to reach for
# whenever you *do* find inconsistent casing/whitespace:
df["Segment"] = df["Segment"].astype(str).str.strip().str.title()
df["Segment"].unique()

In [ ]:
# TODO 1: unique() on Sub-Category


# TODO 2: clean the simulated dirty Series into one consistent value


# TODO 3: comment — why does inconsistent text break groupby later?

In [ ]:
# Range sanity check: Discount should never be negative or above 1 (100%)
print("Discount min/max:", df["Discount"].min(), df["Discount"].max())

# Negative profit is common in this dataset -- a real business signal, not an error
print("Orders sold at a loss:", (df["Profit"] < 0).sum())

In [ ]:
# Visual check for outliers in Sales using a boxplot
plt.figure(figsize=(6, 4))
plt.boxplot(df["Sales"], orientation="horizontal")
plt.title("Sales distribution -- boxplot")
plt.xlabel("Sales")
plt.show()

In [ ]:
# IQR method: flag numeric outliers beyond 1.5x the interquartile range
q1 = df["Sales"].quantile(0.25)
q3 = df["Sales"].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers = df[(df["Sales"] < lower_bound) | (df["Sales"] > upper_bound)]
print(f"Sales outlier bounds: [{lower_bound:.2f}, {upper_bound:.2f}]")
print("Number of Sales outliers:", len(outliers))

In [ ]:
# TODO 1: IQR outlier method applied to Profit


# TODO 2: boxplot for Quantity


# TODO 3: range sanity check on Quantity (min/max)

In [ ]:
# Boolean indexing: orders sold at a loss
loss_orders = df[df["Profit"] < 0]
print("Loss-making orders:", len(loss_orders))
loss_orders[["Order ID", "Product Name", "Sales", "Profit"]].head()

In [ ]:
# Combine multiple conditions with & (remember the parentheses around each condition!)
same_day_west = df[(df["Ship Mode"] == "Same Day") & (df["Region"] == "West")]
same_day_west[["Order ID", "Region", "Ship Mode", "Sales"]].head()

In [ ]:
# .loc for label-based selection: rows where Profit < 0, only a few relevant columns
df.loc[df["Profit"] < 0, ["Order ID", "Category", "Sub-Category", "Profit"]].head()

# .iloc for pure position-based selection: first 5 rows, first 3 columns
df.iloc[:5, :3]

In [ ]:
# TODO 1: Technology orders with Sales > 1000


# TODO 2: .loc selection -- Order ID, Customer Name, Profit where Discount > 0.5


# TODO 3: .iloc -- last 5 rows, last 4 columns


# TODO 4: combine three conditions with &

In [ ]:
# Total profit and sales per Region, sorted from most to least profitable
region_summary = df.groupby("Region", observed=True)[["Sales", "Profit"]].sum().sort_values("Profit", ascending=False)
region_summary

In [ ]:
# Multiple aggregations at once with .agg()
category_summary = df.groupby("Category", observed=True).agg(
    total_sales=("Sales", "sum"),
    avg_profit=("Profit", "mean"),
    orders=("Order ID", "count"),
)
category_summary

In [ ]:
# pivot_table: average Sales by Region (rows) x Category (columns)
pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="mean",
    observed=True,
)
pivot

In [ ]:
# TODO 1: total Profit per Sub-Category, sorted ascending


# TODO 2: pivot table -- Sales by Segment (rows) x Ship Mode (columns)


# TODO 3: average and max Shipping Days per Ship Mode

In [ ]:
# TODO 1: State with highest total Profit, and State with largest total loss


# TODO 2: relationship between Discount (binned) and average Profit


# TODO 3: your own exploration