In [2]:
# Core libraries for this lecture
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# Read the CSV into a DataFrame.
# If this ever raises UnicodeDecodeError on another file, try encoding="latin1".
sales = pd.read_csv("Sample-Superstore2019.csv",
                    parse_dates=['Order Date', 'Ship Date'])
sales.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9994 non-null   int64
 1   Row ID          9994 non-null   int64
 2   Order ID        9994 non-null   str
 3   Order Date      9994 non-null   datetime64[us]
 4   Ship Date       9994 non-null   datetime64[us]
 5   Ship Mode       9994 non-null   str
 6   Customer ID     9994 non-null   str
 7   Customer Name   9994 non-null   str
 8   Segment         9994 non-null   str
 9   Country/Region  9994 non-null   str
 10  City            9994 non-null   str
 11  State           9994 non-null   str
 12  Postal Code     9983 non-null   float64
 13  Region          9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Category        9994 non-null   str
 16  Sub-Category    9994 non-null   str
 17  Product Name    9994 non-null   str
 18  Sales           9994 non-null   float64
 19  Quantity        9994 non-null   int64
 20  Discount        9994 non-null   float64
 21  Profit          9994 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(3), str(13)
memory usage: 8.3 MB

In [7]:
# Quick confirmation that the file loaded and how big it is (rows, columns)
sales.shape

(9994, 22)

In [10]:
sales.head(10)

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,0,1,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,1,2,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,2,3,CA-2018-138688,2018-06-12,2018-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,3,4,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,4,5,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,5,6,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,6,7,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,7,8,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,8,9,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,9,10,CA-2016-115812,2016-06-09,2016-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [8]:
# Shape: (number of rows, number of columns)
print("Shape:", sales.shape)

Shape: (9994, 22)

In [11]:
sales.tail()

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9989,9990,CA-2016-110422,2016-01-21,2016-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9990,9991,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9991,9992,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9992,9993,CA-2019-121258,2019-02-26,2019-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9993,9994,CA-2019-119914,2019-05-04,2019-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [24]:
sales.sample(n=10, random_state=42)

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3125,3125,3126,CA-2017-121720,2017-06-11,2017-06-12,First Class,JE-15610,Jim Epp,Corporate,United States,...,33801.0,South,OFF-ST-10003816,Office Supplies,Storage,Fellowes High-Stak Drawer Files,563.808,4,0.2,21.1428
1441,1441,1442,CA-2019-128160,2019-12-19,2019-12-24,Second Class,MM-17920,Michael Moore,Consumer,United States,...,94110.0,West,OFF-BI-10001510,Office Supplies,Binders,Deluxe Heavy-Duty Vinyl Round Ring Binder,36.672,2,0.2,11.4600
4510,4510,4511,CA-2018-119935,2018-11-10,2018-11-14,Standard Class,KM-16225,Kalyca Meade,Corporate,United States,...,65807.0,Central,FUR-FU-10001085,Furniture,Furnishings,3M Polarizing Light Filter Sleeves,37.300,2,0.0,17.1580
39,39,40,CA-2017-117415,2017-12-27,2017-12-31,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,...,77041.0,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.058,3,0.3,-15.1470
4509,4509,4510,CA-2019-167003,2019-05-23,2019-05-29,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,...,90036.0,West,FUR-TA-10001520,Furniture,Tables,"Lesro Sheffield Collection Coffee Table, End T...",171.288,3,0.2,-6.4233
1599,1599,1600,CA-2019-158876,2019-11-19,2019-11-21,Second Class,AB-10150,Aimee Bixby,Consumer,United States,...,75007.0,Central,OFF-AR-10003373,Office Supplies,Art,"Boston School Pro Electric Pencil Sharpener, 1670",99.136,4,0.2,8.6744
7363,7363,7364,CA-2018-127243,2018-11-28,2018-12-04,Standard Class,DS-13180,David Smith,Corporate,United States,...,19140.0,East,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,340.182,3,0.4,-73.7061
9951,9951,9952,CA-2019-121559,2019-06-01,2019-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,...,46203.0,Central,OFF-BI-10002072,Office Supplies,Binders,Cardinal Slant-D Ring Binders,17.380,2,0.0,8.6900
500,500,501,US-2018-105578,2018-05-30,2018-06-04,Standard Class,MY-17380,Maribeth Yedwab,Corporate,United States,...,80134.0,West,OFF-BI-10001670,Office Supplies,Binders,Vinyl Sectional Post Binders,22.620,2,0.7,-15.0800
4847,4847,4848,CA-2016-164469,2016-06-25,2016-06-27,Second Class,GK-14620,Grace Kelly,Corporate,United States,...,97301.0,West,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,71.632,11,0.2,17.9080

In [26]:
sales.columns.tolist()

['Unnamed: 0',
 'Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country/Region',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [27]:
# Column names
print(sales.columns.tolist())

# .info() gives dtypes + non-null counts + memory usage all at once
sales.info()

['Unnamed: 0', 'Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']
<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9994 non-null   int64
 1   Row ID          9994 non-null   int64
 2   Order ID        9994 non-null   str
 3   Order Date      9994 non-null   datetime64[us]
 4   Ship Date       9994 non-null   datetime64[us]
 5   Ship Mode       9994 non-null   str
 6   Customer ID     9994 non-null   str
 7   Customer Name   9994 non-null   str
 8   Segment         9994 non-null   str
 9   Country/Region  9994 non-null   str
 10  City            9994 non-null   str
 11  State           9994 non-null   str
 12  Postal Code     9983 non-null   float64
 13  Region          9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Category        9994 non-null   str
 16  Sub-Category    9994 non-null   str
 17  Product Name    9994 non-null   str
 18  Sales           9994 non-null   float64
 19  Quantity        9994 non-null   int64
 20  Discount        9994 non-null   float64
 21  Profit          9994 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(3), str(13)
memory usage: 1.7 MB

In [ ]:
# TODO 1: print the column names as a list


# TODO 2: display the first 7 rows


# TODO 3: inspect df.info() output and note the column(s) with missing values (write your answer as a comment)


# TODO 4: re-read the CSV using a read_csv parameter that avoids the Unnamed: 0 column

In [28]:
# Summary stats for numeric columns: Sales, Quantity, Discount, Profit, Postal Code, Row ID...
sales.describe()

,Unnamed: 0,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994,9994,9983.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4996.500000,4997.500000,2018-04-30 10:03:51.979187,2018-05-04 09:03:29.645787,55245.233297,229.858001,3.789574,0.156203,28.656896
min,0.000000,1.000000,2016-01-03 00:00:00,2016-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2498.250000,2499.250000,2017-05-23 00:00:00,2017-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4996.500000,4997.500000,2018-06-26 00:00:00,2018-06-29 00:00:00,57103.000000,54.490000,3.000000,0.200000,8.666500
75%,7494.750000,7495.750000,2019-05-14 00:00:00,2019-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9993.000000,9994.000000,2019-12-30 00:00:00,2020-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,2885.163629,NaN,NaN,32038.715955,623.245101,2.225110,0.206452,234.260108

In [29]:
# Summary stats for text/categorical columns
sales.describe(include="str")

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2019-100111,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48

In [31]:
sales["Region"].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [30]:
# How many orders per Region / Segment / Ship Mode?
print(sales["Region"].value_counts())
print()
print(sales["Segment"].value_counts())
print()
print(sales["Ship Mode"].value_counts())

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [ ]:
# TODO 1: describe() on Sales and Profit only


# TODO 2: value_counts() on Category


# TODO 3: value_counts(normalize=True) on Ship Mode


# TODO 4: comment on whether Discount's min/max look plausible

In [33]:
# sales['Order Date'] = pd.to_datetime(sales['Order Date'])
sales["Shipping Days"] =(sales['Ship Date'] - sales['Order Date']).dt.days

In [37]:
sales['Ship Date'].dt.day

0       11
1       11
2       16
3       18
4       18
        ..
9989    23
9990     3
9991     3
9992     3
9993     9
Name: Ship Date, Length: 9994, dtype: int32

In [34]:
sales.head()

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days
0,0,1,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3
1,1,2,CA-2018-152156,2018-11-08,2018-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3
2,2,3,CA-2018-138688,2018-06-12,2018-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4
3,3,4,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7
4,4,5,US-2017-108966,2017-10-11,2017-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7

In [38]:
# Convert the two date columns from text to real datetime objects
sales["Order Date"] = pd.to_datetime(sales["Order Date"])
sales["Ship Date"] = pd.to_datetime(sales["Ship Date"])

# Now that they're real dates, we can do date arithmetic:
# how many days did each order take to ship?
sales["Shipping Days"] = (sales["Ship Date"] - sales["Order Date"]).dt.days

sales[["Order Date", "Ship Date", "Shipping Days"]].head()

  Order Date  Ship Date  Shipping Days
0 2018-11-08 2018-11-11              3
1 2018-11-08 2018-11-11              3
2 2018-06-12 2018-06-16              4
3 2017-10-11 2017-10-18              7
4 2017-10-11 2017-10-18              7

In [39]:
sales.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9994 non-null   int64
 1   Row ID          9994 non-null   int64
 2   Order ID        9994 non-null   str
 3   Order Date      9994 non-null   datetime64[us]
 4   Ship Date       9994 non-null   datetime64[us]
 5   Ship Mode       9994 non-null   str
 6   Customer ID     9994 non-null   str
 7   Customer Name   9994 non-null   str
 8   Segment         9994 non-null   str
 9   Country/Region  9994 non-null   str
 10  City            9994 non-null   str
 11  State           9994 non-null   str
 12  Postal Code     9983 non-null   float64
 13  Region          9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Category        9994 non-null   str
 16  Sub-Category    9994 non-null   str
 17  Product Name    9994 non-null   str
 18  Sales           9994 non-null   float64
 19  Quantity        9994 non-null   int64
 20  Discount        9994 non-null   float64
 21  Profit          9994 non-null   float64
 22  Shipping Days   9994 non-null   int64
dtypes: datetime64[us](2), float64(4), int64(4), str(13)
memory usage: 8.4 MB

In [41]:
sales.memory_usage(deep=True)

Index                132
Unnamed: 0         79952
Row ID             79952
Order ID          629622
Order Date         79952
Ship Date          79952
Ship Mode         617860
Customer ID       569658
Customer Name     620659
Segment           578027
Country/Region    619628
City              582957
State             574527
Postal Code        79952
Region            538271
Product ID        639616
Category          617655
Sub-Category      561580
Product Name      865680
Sales              79952
Quantity           79952
Discount           79952
Profit             79952
Shipping Days      79952
dtype: int64

In [42]:
sales["Country/Region"] = sales["Country/Region"].astype("category")

In [43]:
sales.memory_usage(deep=True)

Index                132
Unnamed: 0         79952
Row ID             79952
Order ID          629622
Order Date         79952
Ship Date          79952
Ship Mode         617860
Customer ID       569658
Customer Name     620659
Segment           578027
Country/Region     10056
City              582957
State             574527
Postal Code        79952
Region            538271
Product ID        639616
Category          617655
Sub-Category      561580
Product Name      865680
Sales              79952
Quantity           79952
Discount           79952
Profit             79952
Shipping Days      79952
dtype: int64

In [44]:
# Pull the order month/year out now that Order Date is a real datetime
# sales["Order Month"] = sales["Order Date"].dt.month
# sales["Order Year"] = sales["Order Date"].dt.year

# Convert low-cardinality text columns to the 'category' dtype (memory + speed win)
for col in ["Segment", "Region", "Ship Mode", "Category", "Sub-Category"]:
    sales[col] = sales[col].astype("category")

sales.memory_usage(deep=True)

Index                132
Unnamed: 0         79952
Row ID             79952
Order ID          629622
Order Date         79952
Ship Date          79952
Ship Mode          10235
Customer ID       569658
Customer Name     620659
Segment            10169
Country/Region     10056
City              582957
State             574527
Postal Code        79952
Region             10210
Product ID        639616
Category           10175
Sub-Category       10955
Product Name      865680
Sales              79952
Quantity           79952
Discount           79952
Profit             79952
Shipping Days      79952
dtype: int64

In [45]:
sales.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9994 non-null   int64
 1   Row ID          9994 non-null   int64
 2   Order ID        9994 non-null   str
 3   Order Date      9994 non-null   datetime64[us]
 4   Ship Date       9994 non-null   datetime64[us]
 5   Ship Mode       9994 non-null   category
 6   Customer ID     9994 non-null   str
 7   Customer Name   9994 non-null   str
 8   Segment         9994 non-null   category
 9   Country/Region  9994 non-null   category
 10  City            9994 non-null   str
 11  State           9994 non-null   str
 12  Postal Code     9983 non-null   float64
 13  Region          9994 non-null   category
 14  Product ID      9994 non-null   str
 15  Category        9994 non-null   category
 16  Sub-Category    9994 non-null   category
 17  Product Name    9994 non-null   str
 18  Sales           9994 non-null   float64
 19  Quantity        9994 non-null   int64
 20  Discount        9994 non-null   float64
 21  Profit          9994 non-null   float64
 22  Shipping Days   9994 non-null   int64
dtypes: category(6), datetime64[us](2), float64(4), int64(4), str(7)
memory usage: 5.1 MB

In [ ]:
# TODO 1: confirm Order Date's dtype


# TODO 2: create an "Order Weekday" column using .dt.day_name()


# TODO 3: compute the average Shipping Days


# TODO 4: convert Sub-Category to category dtype

In [48]:
# Count missing values per column
sales.isnull().sum()

Unnamed: 0         0
Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State              0
Postal Code       11
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
Shipping Days      0
dtype: int64

In [51]:
sales[sales['Postal Code'].isnull()][["Country/Region", "Region", "State", "City"]]

     Country/Region Region    State        City
2234  United States   East  Vermont  Burlington
5274  United States   East  Vermont  Burlington
8798  United States   East  Vermont  Burlington
9146  United States   East  Vermont  Burlington
9147  United States   East  Vermont  Burlington
9148  United States   East  Vermont  Burlington
9386  United States   East  Vermont  Burlington
9387  United States   East  Vermont  Burlington
9388  United States   East  Vermont  Burlington
9389  United States   East  Vermont  Burlington
9741  United States   East  Vermont  Burlington

In [ ]:
# Look at the actual rows with a missing Postal Code — is there a pattern?
sales[sales["Postal Code"].isnull()][["City", "State", "Postal Code"]]

In [52]:
# All 11 missing postal codes belong to Burlington, Vermont.
# That's not random -- we can look up the real ZIP code (05401) and fill it in
# rather than dropping 11 otherwise-perfectly-good rows.
sales["Postal Code"] = sales["Postal Code"].fillna(5401)

# Confirm there are no missing values left in this column
sales["Postal Code"].isnull().sum()

np.int64(0)

In [53]:
sales.isnull().sum()

Unnamed: 0        0
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State             0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
Shipping Days     0
dtype: int64

In [ ]:
# TODO 1: confirm no missing values remain


# TODO 2: write (but don't overwrite df with) a dropna() call for Postal Code


# TODO 3: comment — when is dropping rows the wrong call?

In [ ]:
# Exact full-row duplicates
print("Exact duplicate rows:", df.duplicated().sum())

# Duplicates on a more meaningful subset: same order line for the same product
print("Duplicate Order ID + Product ID pairs:", df.duplicated(subset=["Order ID", "Product ID"]).sum())

In [ ]:
# Inspect what those subset-duplicates actually look like
dup_mask = df.duplicated(subset=["Order ID", "Product ID"], keep=False)
df[dup_mask].sort_values(["Order ID", "Product ID"]).head(8)

In [ ]:
# TODO 1: duplicated() on Customer ID + Order Date


# TODO 2: comment explaining keep="first" vs keep="last"


# TODO 3: name (and try) the method that would actually remove duplicate rows

In [ ]:
# Check every key categorical column for stray variants (casing, whitespace, typos)
for col in ["Segment", "Region", "Ship Mode", "Category", "Country/Region"]:
    print(col, "->", df[col].unique())

In [ ]:
# Even on a clean column, this is the defensive pattern to reach for
# whenever you *do* find inconsistent casing/whitespace:
df["Segment"] = df["Segment"].astype(str).str.strip().str.title()
df["Segment"].unique()

In [ ]:
# TODO 1: unique() on Sub-Category


# TODO 2: clean the simulated dirty Series into one consistent value


# TODO 3: comment — why does inconsistent text break groupby later?

In [ ]:
# Range sanity check: Discount should never be negative or above 1 (100%)
print("Discount min/max:", df["Discount"].min(), df["Discount"].max())

# Negative profit is common in this dataset -- a real business signal, not an error
print("Orders sold at a loss:", (df["Profit"] < 0).sum())

In [ ]:
# Visual check for outliers in Sales using a boxplot
plt.figure(figsize=(6, 4))
plt.boxplot(df["Sales"], orientation="horizontal")
plt.title("Sales distribution -- boxplot")
plt.xlabel("Sales")
plt.show()

In [ ]:
# IQR method: flag numeric outliers beyond 1.5x the interquartile range
q1 = df["Sales"].quantile(0.25)
q3 = df["Sales"].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers = df[(df["Sales"] < lower_bound) | (df["Sales"] > upper_bound)]
print(f"Sales outlier bounds: [{lower_bound:.2f}, {upper_bound:.2f}]")
print("Number of Sales outliers:", len(outliers))

In [ ]:
# TODO 1: IQR outlier method applied to Profit


# TODO 2: boxplot for Quantity


# TODO 3: range sanity check on Quantity (min/max)

In [ ]:
# Boolean indexing: orders sold at a loss
loss_orders = df[df["Profit"] < 0]
print("Loss-making orders:", len(loss_orders))
loss_orders[["Order ID", "Product Name", "Sales", "Profit"]].head()

In [ ]:
# Combine multiple conditions with & (remember the parentheses around each condition!)
same_day_west = df[(df["Ship Mode"] == "Same Day") & (df["Region"] == "West")]
same_day_west[["Order ID", "Region", "Ship Mode", "Sales"]].head()

In [ ]:
# .loc for label-based selection: rows where Profit < 0, only a few relevant columns
df.loc[df["Profit"] < 0, ["Order ID", "Category", "Sub-Category", "Profit"]].head()

# .iloc for pure position-based selection: first 5 rows, first 3 columns
df.iloc[:5, :3]

In [ ]:
# TODO 1: Technology orders with Sales > 1000


# TODO 2: .loc selection -- Order ID, Customer Name, Profit where Discount > 0.5


# TODO 3: .iloc -- last 5 rows, last 4 columns


# TODO 4: combine three conditions with &

In [ ]:
# Total profit and sales per Region, sorted from most to least profitable
region_summary = df.groupby("Region", observed=True)[["Sales", "Profit"]].sum().sort_values("Profit", ascending=False)
region_summary

In [ ]:
# Multiple aggregations at once with .agg()
category_summary = df.groupby("Category", observed=True).agg(
    total_sales=("Sales", "sum"),
    avg_profit=("Profit", "mean"),
    orders=("Order ID", "count"),
)
category_summary

In [ ]:
# pivot_table: average Sales by Region (rows) x Category (columns)
pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="mean",
    observed=True,
)
pivot

In [ ]:
# TODO 1: total Profit per Sub-Category, sorted ascending


# TODO 2: pivot table -- Sales by Segment (rows) x Ship Mode (columns)


# TODO 3: average and max Shipping Days per Ship Mode

In [ ]:
# TODO 1: State with highest total Profit, and State with largest total loss


# TODO 2: relationship between Discount (binned) and average Profit


# TODO 3: your own exploration